# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cad963f1c15030ee6debbdddec34e4a44e21b45094554d4a3bd9f816db15ff91fcf006a406498e29f03ffc155f0cdc07f9989fb3e0d3dfac2ea81ba13de8bb0

test:
  secret_key_base: e5dd7f22e3ffdb09fec43e174eac7740dd344b728e77ac2d8aa24cae5adf106dc50e5c015e55a2f1c0595f96e354cbaa4044b54744d5a58f0b2c2dbb002b48d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
